/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rcnqouasbetqugbjghsi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbnFvdWFzYmV0cXVnYmpnaHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNTU0NTQsImV4cCI6MjA3OTkzMTQ1NH0.15INHFmJ_Q-GSn0dZVWm4VDU-JCZ5s2KLNd5UYg2NR0"